// Generated by scripts/generate_contracts.py. Do not edit manually.
export type DownloadErrorCode = 'invalid_platform_input' | 'missing_dependency' | 'subprocess_failure' | 'internal_error'

export type DownloadStartErrorCode = 'unsupported_platform'

export type DownloadDownloadingEvent = {
  status: 'downloading'
  log?: string
  progress?: number | null
}

export type DownloadCompletedEvent = {
  status: 'completed'
  message: string
  progress?: number | null
}

export type DownloadErrorEvent = {
  status: 'error'
  code: DownloadErrorCode
  message: string
}

export type DownloadStreamEvent =
  | DownloadDownloadingEvent
  | DownloadCompletedEvent
  | DownloadErrorEvent

export type ErrorDetailResponse = {
  code: DownloadStartErrorCode
  detail: string
}

export type PreflightCheck = {
  ok: boolean
  value?: string | null
  hint?: string | null
  required_for?: string | null
}

export type PreflightResponse = {
  status: 'ok' | 'degraded'
  status_message: string
  checks: Record<string, PreflightCheck>
}
