// This file is auto-generated by @hey-api/openapi-ts

export const DownloadRequestSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        quality: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quality',
            default: '1'
        },
        format: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['mp4', 'mp3']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Format',
            default: 'mp4'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'DownloadRequest'
} as const;

export const DownloadResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        output: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Output'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Path'
        }
    },
    type: 'object',
    required: ['success', 'message'],
    title: 'DownloadResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;