// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { DownloadMediaApiDownloadPostData, DownloadMediaApiDownloadPostError, DownloadMediaApiDownloadPostResponse, ReadRootGetError, ReadRootGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Download Media
 * Download media from supported platforms.
 */
export const downloadMediaApiDownloadPost = <ThrowOnError extends boolean = false>(options: Options<DownloadMediaApiDownloadPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<DownloadMediaApiDownloadPostResponse, DownloadMediaApiDownloadPostError, ThrowOnError>({
        ...options,
        url: '/api/download/'
    });
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadRootGetResponse, ReadRootGetError, ThrowOnError>({
        ...options,
        url: '/'
    });
};