// This file is auto-generated by @hey-api/openapi-ts

export type DownloadRequest = {
    url: string;
    quality?: (string | null);
    format?: ('mp4' | 'mp3' | null);
};

export type DownloadResponse = {
    success: boolean;
    message: string;
    output?: (string | null);
    error?: (string | null);
    file_path?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DownloadMediaApiDownloadPostData = {
    body: DownloadRequest;
};

export type DownloadMediaApiDownloadPostResponse = (DownloadResponse);

export type DownloadMediaApiDownloadPostError = (HTTPValidationError);

export type ReadRootGetResponse = (unknown);

export type ReadRootGetError = unknown;