import json
from pathlib import Path
from typing import get_args

from pydantic import TypeAdapter

from api.models.schemas import (
    DownloadErrorEvent,
    DownloadRuntimeErrorCode,
    DownloadStartErrorCode,
    DownloadStreamEvent,
    ErrorDetailResponse,
    PreflightCheck,
    PreflightResponse,
)


PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
CONTRACTS_DIR = PROJECT_ROOT / "contracts"
CONTRACT_SCHEMA_PATH = CONTRACTS_DIR / "download-contract.schema.json"
FRONTEND_CONTRACT_PATH = PROJECT_ROOT / "web-client" / "src" / "features" / "download" / "generated-contract.ts"


def _literal_values(type_alias: object) -> tuple[str, ...]:
    return tuple(str(value) for value in get_args(type_alias))


def _render_literal_union(values: tuple[str, ...]) -> str:
    return " | ".join(f"'{value}'" for value in values)


def build_contract_schema() -> dict[str, object]:
    return {
        "downloadRuntimeErrorCode": list(_literal_values(DownloadRuntimeErrorCode)),
        "downloadStartErrorCode": list(_literal_values(DownloadStartErrorCode)),
        "downloadStreamEvent": TypeAdapter(DownloadStreamEvent).json_schema(),
        "downloadErrorEvent": DownloadErrorEvent.model_json_schema(),
        "errorDetailResponse": ErrorDetailResponse.model_json_schema(),
        "preflightCheck": PreflightCheck.model_json_schema(),
        "preflightResponse": PreflightResponse.model_json_schema(),
    }


def render_typescript_contract() -> str:
    runtime_codes = _render_literal_union(_literal_values(DownloadRuntimeErrorCode))
    start_codes = _render_literal_union(_literal_values(DownloadStartErrorCode))

    return f"""// Generated by scripts/generate_contracts.py. Do not edit manually.
export type DownloadErrorCode = {runtime_codes}

export type DownloadStartErrorCode = {start_codes}

export type DownloadDownloadingEvent = {{
  status: 'downloading'
  log?: string
  progress?: number | null
}}

export type DownloadCompletedEvent = {{
  status: 'completed'
  message: string
  progress?: number | null
}}

export type DownloadErrorEvent = {{
  status: 'error'
  code: DownloadErrorCode
  message: string
}}

export type DownloadStreamEvent =
  | DownloadDownloadingEvent
  | DownloadCompletedEvent
  | DownloadErrorEvent

export type ErrorDetailResponse = {{
  code: DownloadStartErrorCode
  detail: string
}}

export type PreflightCheck = {{
  ok: boolean
  value?: string | null
  hint?: string | null
  required_for?: string | null
}}

export type PreflightResponse = {{
  status: 'ok' | 'degraded'
  status_message: string
  checks: Record<string, PreflightCheck>
}}
"""


def write_contract_artifacts() -> tuple[Path, Path]:
    CONTRACTS_DIR.mkdir(parents=True, exist_ok=True)
    FRONTEND_CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)

    CONTRACT_SCHEMA_PATH.write_text(
        json.dumps(build_contract_schema(), indent=2) + "\n",
        encoding="utf-8",
    )
    FRONTEND_CONTRACT_PATH.write_text(render_typescript_contract(), encoding="utf-8")

    return CONTRACT_SCHEMA_PATH, FRONTEND_CONTRACT_PATH
